# Travis-CI Build (adapted fro keyczar-dotnet example)

language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VER="2.10.11"
  - MONO_VER="3.10.0"

before_install:
 - sh .ci/install-mono-${MONO_VER}.sh

script:
 - xbuild 
 - .ci/RunTests.sh 

branches:
 only:
  - master
